server:
  port: 1203
  error:
    path: /error
  servlet:
    context-path: /proxy
    session:
      timeout: 3H
    application-display-name: 代理IP服务

spring:
  application:
    name: 代理IP服务-开发环境
  mvc:
    view:
      suffix: .jsp
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/proxy_ip_pool?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 连接池
    hikari:
      #连接池名
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 800
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 3000
      connection-test-query: SELECT 1

logging:
  config: classpath:logback-test.xml
  file:
    name: logs\proxy_log.log
  level:
    root: info # trace < debug < info < warn < error < fatal

mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: simple
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: null
    default-statement-timeout: 900
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

proxy:
  local-ip: 192.168.2.103